ランタイムでもゲーム開始時に変数を破棄できるように
kugimasa/UnityTeamDevTemplate pull request #21
Opened 2021-02-18 10:40 UTC by Ruchi12377

ランタイムでもゲーム開始時に変数をはきできるようにしました。
結構適当に作ったのでバグフィックスなどはまだ完璧じゃないです。

確認よろしくおねがいします。

2021-02-20 13:07 UTC, Ruchi12377 commented on Assets/SilCilSystem/Core/Variables/Variables.cs
> +            #endif
エディターで再生してない場合に初期化されない

2021-02-21 11:04 UTC, kugimasa requested changes

2021-02-21 11:04 UTC, kugimasa commented on Assets/SilCilSystem/Core/Variables/Variables.cs
> +<<<<<<< Updated upstream
コンフリしたファイルがcommitされているようなので修正をお願いします:pray:

2021-02-21 11:04 UTC, kugimasa commented on Assets/SilCilSystem/Editor/Packages/Variables/CustomEditors/VariableAsset/VariableAssetEditor.cs
> +<<<<<<< Updated upstream
こちらも同様

2021-02-21 11:04 UTC, kugimasa commented on Assets/_Assets/SampleGames/RollBall/Variables/Count.asset
> +<<<<<<< Updated upstream
こちらも同様

2021-02-21 11:04 UTC, kugimasa commented on Assets/_Assets/SampleGames/RollBall/Variables/IsPlaying.asset
> +<<<<<<< Updated upstream
こちらも同様

2021-02-21 15:53 UTC, Ruchi12377 commented on Assets/SilCilSystem/Core/Variables/Variables.cs
> +            #endif
修正済み

2021-02-21 15:55 UTC, Ruchi12377 commented
コンフリクトしたファイルがコミットされてるのを修正。
エディタで再生してないときに値が初期化されないバグを修正(ビルドして確認済み(Win-64bit)

2021-03-14 13:23 UTC, kugimasa approved these changes
@Ruchi12377 遅くなりました...!! 修正ありがとうございます!! LGTMです!

2021-03-14 13:23 UTC, merged